// tag::DE[]
=== Ziel des Advanced Product Owner Curriculums

Das Advanced Product Owner Curriculum bietet ein Open-Source, framework-neutrales Trainingsschema mit einer entsprechenden Zertifizierung.

Das Hauptziel des Advanced Product Owner Curriculums ist es, die Zusammenhänge und Wechselwirkungen zwischen Methoden und Werkzeugen des agilen Produktmanagements zu vermitteln. Die Teilnehmer sollen befähigt werden, die Eignung dieser Werkzeuge und Methoden für ihren jeweiligen Kontext zu beurteilen und erfolgreich anzuwenden.

// end::DE[]

// tag::EN[]
=== Goal of Advanced Product Owner Curriculum

The Advanced Product Owner curriculum provides an open-source, framework-neutral training scheme with a corresponding certification.

The main goal of the Advanced Product Owner curriculum is to convey the interrelationships and interactions between methods and tools of agile product management.
Participants should be enabled to assess the suitability of these tools and methods for their respective context and to apply them successfully.
// end::EN[]

