// tag::DE[]
===  Structure of Learning Objectives

The Advanced Product Owner curriculum distinguishes between three levels of competence and three kinds of ability.
All three levels of competence are tested in the examination, one third each

The three competence levels are

[NOTE]
====
**Competence Level 1** focuses on specific tools or methods related to the learning objective.
At competence level 1, neither combinations of tools and methods nor their relations to the working context are relevant.
====

[NOTE]
====
**Competence Level 2** focuses on the relationships between two tools or methods and the relationship of a single tool or method to the working context.
====

[NOTE]
====
**Competence Level 3** focuses on relationships between more than two tools or methods and on the relationship of combinations of tools and methods to the working context.
====

The three kinds of abilities are

[NOTE]
====
**Knowing something** is about facts and figures about a tool or method.
The knowledge that may be assessed is, for example, about the elements that make up a tool or the phases of a methods.
Knowledge about the history of methods or sources is not part of the examination.
====

[NOTE]
====
**Being aware of something** is about being able to anticipate how a tool or method might be used.
Anticipation is also relevant when deciding not to use a tool or method.
In addition, being aware addresses the consequences of using different versions or templates of tools or methods and of combinations of tools and methods.
====

[NOTE]
====
**Being able to do something** is about deciding about or applying tools and methods according to the working context.
This can mean both that product owners apply the tools or methods themselves and that they let their team apply the tools or methods.
====
// end::DE[]

// tag::EN[]
===  Structure of Learning Objectives

The Advanced Product Owner curriculum distinguishes between three levels of competence and three kinds of ability.
All three levels of competence are tested in the examination, one third each

The three competence levels are

[NOTE]
====
**Competence Level 1** focuses on specific tools or methods related to the learning objective.
At competence level 1, neither combinations of tools and methods nor their relations to the working context are relevant.
====

[NOTE]
====
**Competence Level 2** focuses on the relationships between two tools or methods and the relationship of a single tool or method to the working context.
====

[NOTE]
====
**Competence Level 3** focuses on relationships between more than two tools or methods and on the relationship of combinations of tools and methods to the working context.
====

The three kinds of abilities are

[NOTE]
====
**Knowing something** is about facts and figures about a tool or method.
The knowledge that may be assessed is, for example, about the elements that make up a tool or the phases of a methods.
Knowledge about the history of methods or sources is not part of the examination.
====

[NOTE]
====
**Being aware of something** is about being able to anticipate how a tool or method might be used.
Anticipation is also relevant when deciding not to use a tool or method.
In addition, being aware addresses the consequences of using different versions or templates of tools or methods and of combinations of tools and methods.
====

[NOTE]
====
**Being able to do something** is about deciding about or applying tools and methods according to the working context.
This can mean both that product owners apply the tools or methods themselves and that they let their team apply the tools or methods.
====
// end::EN[]

